apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: studycase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend-flask-postgres:1.0
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: appdb
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: studycase
spec:
  selector:
    app: backend
  ports:
  - port: 5000
