apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: studycase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          value: appdb
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}   # untuk latihan (tidak persistent)

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: studycase
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
